### ISSUE TITLE
Feature suggestion: Travelling from on-curve nodes to segment nodes

### ISSUE THREAD

**Issue by gorjious** [florianpircher/Keyboard-Selection-Travel#1]
This is brilliant! It is such an efficient way of selecting instead of constantly using the mouse/trackpad to drag. I was looking for something like this so I had started a script that would cycle through the nodes along the outline but then ran into difficulty going across outlines. Your approach cuts through all of that.

If I can make a suggestion/wish. 
I constantly find myself either selecting a single on-curve node or both the off-curve nodes of a curved segment.
Would it be possible to add a feature that allows for travelling from an on-curve node to segment nodes? I've been trying the multiple selection feature but it doesn't feel as predictable. If this was possible, I could almost drop the use of a trackpad while editing outlines.

**Comment by florianpircher** [comment]
Glad you like it! Just to make sure I understand correctly: you want to toggle between on-curve node selected to both of it’s off-curve handles selected.

So, from this:

<img width="222" alt src="https://user-images.githubusercontent.com/3776198/114745252-c9961c00-9d4e-11eb-844a-a37519244455.png">

to this:

<img width="222" alt src="https://user-images.githubusercontent.com/3776198/114745297-cef36680-9d4e-11eb-852c-5b4d14993fd8.png">

and the other way around? ***Or***, to this and back:

<img width="222" alt src="https://user-images.githubusercontent.com/3776198/114745787-5345e980-9d4f-11eb-9909-6ca6dc183d3a.png">

**Comment by gorjious** [comment]
I was thinking this.

<img width="486" alt="Screenshot 2021-04-14 at 10 28 56" src="https://user-images.githubusercontent.com/23149420/114745842-523f9880-9d0c-11eb-9c1c-5d6b98a355ba.png">
<img width="470" alt="Screenshot 2021-04-14 at 10 29 02" src="https://user-images.githubusercontent.com/23149420/114745843-52d82f00-9d0c-11eb-8afd-64232acb0deb.png">

Not sure if the multiple selection feature would always keep these neatly in sync.

<img width="471" alt="Screenshot 2021-04-14 at 10 29 13" src="https://user-images.githubusercontent.com/23149420/114745847-5370c580-9d0c-11eb-8d96-eedcf658cfbf.png">
<img width="472" alt="Screenshot 2021-04-14 at 10 29 22" src="https://user-images.githubusercontent.com/23149420/114745851-54095c00-9d0c-11eb-9f4c-233c0827b2be.png">

**Comment by florianpircher** [comment]
This can go into a script, no plugin needed. I’ll try adding that to my scripts collection. Stay tuned :)

**Comment by gorjious** [comment]
Would you still be able to freely travel across the on-curve nodes and segments like this?

![animated](https://user-images.githubusercontent.com/23149420/114747738-671d2b80-9d0e-11eb-83c1-9756c47fb775.gif)

**Comment by florianpircher** [comment]
My current idea is to add scripts that you can assign custom shortcuts in preferences. So Keyboard Selection Travel would still work. The scripts would be something like: “Select Handles to the Right/Left/Top/Bottom” and “Select Handles Node to the Right/Left/Top/Bottom”.

**Comment by gorjious** [comment]
Cool. I'll keep my eyes open for those!

**Comment by florianpircher** [comment]
The scripts are up! There are four scripts, one for left, right, up, and down.

https://github.com/florianpircher/Glyphs-Scripts/tree/main/Scripts/Selection/Travel

This is what it looks like:

![](https://user-images.githubusercontent.com/3776198/114790915-dbdf7c80-9d85-11eb-9e9d-1e284e52d925.gif)

For these scripts to be useful, you’ll need to define shortcuts in the preferences. This my setup:

<img width="878" alt src="https://user-images.githubusercontent.com/3776198/114791091-24973580-9d86-11eb-9abc-da9d15a97eae.png">

Installation of the scripts somewhat tricky. If you know what to do, great! If not, I will try to get my scripts collection added to the plugin manager in the following days. That would make the installation a lot easier.

**Comment by gorjious** [comment]
Got the scripts all set-up and working in conjunction with the plugin. 
I'll have to share with you how I'm using it once I get a good workflow going.
Thank you, Florian!

**Comment by florianpircher** [comment]
The scripts are now downloadable from the Plugin Manager.
